.github/pr-labeler.yml, .github/renovate.json, .github/workflows/pr-labeler.yml
=> Add github workflows

api_monitor.sh
The user time is more reliable, due to background activities
from booting.
We had not included the time it takes for iperf, fullconntest, LB test
in the total cycle time, thus painting a wrong picture ... fixed.
Also report used images in report.
=> Add and report test time, rep user time for pibench.

api_monitor.sh
This implements feature issue #16.
=> Attach iteration number to alarm messages.

api_monitor.sh, run_gx_scs.sh
=> Nicer way of coloring status. Use Ubuntu for gx-scs.

scripts/push.sh
=> github: add missing push.sh script

README.md
=> README: minor enhancements

Dockerfile
=> docker: merge RUN commands

Dockerfile
=> docker: make api_monitor.sh

api_monitor.sh
=> Use DATADIR for ssh keypairs

Dockerfile
=> docker: logs -> data

Dockerfile
=> docker: install openssh-client

api_monitor.sh
Also slightly increase network timeout again.
=> Add minimal cycle time, sleep if below.

api_monitor.sh
=> Move interruption before stats sending, so we don't lose it.

api_monitor.sh
=> Avoid using 9.9.9.9 as DNS by default.

Dockerfile
The included command line will do 5 iterations with a good set of tests,
which should take ~40mins on a typical cloud.
=> Use xena openstackclient. Full api_monitor command line.

api_monitor.sh
This allows further subnet/network cleanup to succeed.
=> If LBs can't be deleted, remove the (VIP) port.

api_monitor.sh, dashboard/openstack-health-dashboard.json
=> Report lbaas actions as octavia, not neutron.

api_monitor.sh
=> Avoid mangling logfile name.

.github/workflows/build-container-image.yml
Signed-off-by: Eduard Itrich <eduard@itrich.net>
=> Switch to main branch

dashboard/openstack-health-dashboard.json, run_wave.sh
=> Add wrapper to run HM on wavestack and dashboard selection.

api_monitor.sh
We send this to telegraf/influx/grafana, so we should maybe also report
it on the console.
=> Report total iteration duration as percentage of max.

dashboard/openstack-health-dashboard.json
We might otherwise overlook things that are significantly wrong ...
=> Add iperf3 gauge in top line.

api_monitor.sh
Our logic to filter only for our own subnets was broken. It now works.
=> Avoid removing lb-vrrp ports from wrong subnets.

api_monitor.sh
=> Error reporting had an echo command missing in error case.

README.md, dashboard/README.md
=> Improve dashboard setup documentation.

dashboard/openstack-health-dashboard.json
=> Rearrange dashboards in errors and bench sections.

api_monitor.sh
In gx-scs currently, the Loadbalancer service is extremely slow. When createing the LB instance (with two amphorae), we time out in the creation API call (which does NOT wait for them to become active). So we end up testing without the LB test. However, the LBs eventually come up and we fail to expect this and fail to clean up. So more and more LBs are hanging around until the 200 iterations are over. We also fail to cleanup networks by consequence.
Change this: In cleanup, if LBs are enabled at all, but there were errors, looks for LBs and try to delete them. So we stop collecting them and also avoid failed network and router cleanup.
=> Cleanup LBs when Octavia times out.

api_monitor.sh
=> Use new v2 flavor names as default flavors.

api_monitor.sh
export CACERT="--os-cacert FILE.crt" can be set if needed. (This allows running against a CiaB system.)
=> Allow setting a CA certificate.

dashboard/openstack-health-dashboard-10.json, dashboard/openstack-health-dashboard.json
log2 4 -- 256 for wait resources
log2 0.0625 -- 128 for benchmarks
=> Use log2 scale and better ranges for wait & bench.

docs/Debian12-Install.md, run_ciab.sh, run_in_loop_pluspco.sh
Spellchecker.
xz-utils -> zstd
Strip embedded \r from IMGUUID (openstackclient dependent)
=> Improve wording of docs.

.gitignore, run_in_loop_poc-wgcloud.sh, run_poc-wgcloud.sh, startup/run-apimon-in-tmux.sh
Shouldn't be merged IMHO, because it overrides previous behavior in `run-apimon-in-tmux.sh`. I have just put it here for reference and as a backup.
=> OSHM setup for `poc-wgcloud`

api_monitor.sh, run_gx_scs.sh
Store data (logfile, ssh keypairs, known_host, user-data) in $DATADIR, which defaults to being cloud-name specific now.
This avoids conflicts when several instances against several environments are started from the same directory on the same server.
Supercedes #195.
=> 1.110: Feat/datadir per cloud

run_pluspco.sh, run_pluspco2.sh, run_pluspco3.sh, run_pluspco4.sh
This avoids bounces if the recipient is unreachable due to the sender being identical.
=> Change sender address.

api_monitor.sh
Testing with an openSUSE 15.6 image showed a few weaknesses:
* scp requires -O to work with older distros
* distros may disallow ssh login until cloud_init has finished, so we need to retry longer
* Pass pkg_upgrade: false to speed up boot time.
Making ssh try harder lead to some nice refactoring into waitssh().
Bump version to 1.112.
=> Retry ssh conn harder. Avoid pkg_upgrade. scp -O.
