SovereignCloudStack/openstack-health-monitor

LICENSE
api_monitor.sh

Sidenote: While CC is not typically recommended for code, the reasons
for it are not very strong in the context of a shell script, where the
code is the source code.
Fixes issue #19.

Include CC-BY-SA-4.0 license text.

---

Dockerfile

docker: use /api_monitor.sh as entrypoint

---

Dockerfile

docker: use 45000 as uid/gid

---

Dockerfile

This solves: "ping: permission denied (are you root?)"

docker: install iputils

---

Dockerfile

`curl` is used inside of the `api_monitor.sh` script, so it should be added to the container image.
Signed-off-by: Joshua Mühlfort <muehlfort@gonicus.de>

Add curl in container image

---

api_monitor.sh

The busybox `date` yields different results than the GNU coreutils `date`. Specifically, it does not seem to expand `%N` to nanoseconds, which seems to cause incorrect time mappings inside of telegraf.
Omitting the date altogether makes telegraf (in the version that I tested) adding it automatically, which should be fine for this use case.
CC @berendt @garloff 
Signed-off-by: Joshua Mühlfort <muehlfort@gonicus.de>

Remove explicit date in influxdb writes

---

Dockerfile

This will avoid cryptography failing due to missing rustc.

Upgrade pip3 when building container.

---

api_monitor.sh

For some reason we observe LBs and Routers that lack the tags
they should have received during creation.
This will need to be investigated another day.
For now just don't filter by tag for those resources, as we
can reliably identify them by name.

Ignore tagging when finding routers and lbs to delete.

---

api_monitor.sh

Sanitize locales, so the decimal dot is understood always.

---

api_monitor.sh

Ocatvia occasionally leaks ports. We currently don't handle them, so
they stay around and prevent the cleanup of subnets and networks, thus
potentially making us run against the network quota.
Identify and delete them.

Find ports leaked by octavia and delete them.

---

api_monitor.sh

The tagging is not as reliable as we'd need it to be :-(
So put a description to floating IPs in addition.
This could be used to automatically clean them up from time to time.
(This cleanup is not yet implemented.)
Note: There were a few neutron floating-ip-XXX commands in the source
file (with XXX = create, list, delete). These won't work, as they need
to be written floatingip-XXX. This was harmless thus far, as we
typically translate these commands into openstack CLI commands (where
they become openstack floating ip XXX) and the translator was tolerant
against the extra dash. This was corrected.

Add description to floating IPs.

---

api_monitor.sh
run_pluspco.sh

By arbitrarily killing backend processes (that serve the http port),
we check whether the LB's health monitor does detect this, goes
into DEGRADED mode and only circles through the ONLINE members.
We now support testing either TCP `-LL` or HTTP `-L` loadbalancers.
Version 1.79.

Kill backends and check LB effectiveness.

---

api_monitor.sh

When creating several networks with VMs, we can distribute them into different AZs.
Unless overridden by the openstack-health-monitor operator, we should use the --compute AZs for this, not the superset of volume, compute and network azs. Most notably, we may have an overarching network AZ with it's own name and this should not break the auto-detection.
Use --volume AZs.

Use --compute availability zones.

---

api_monitor.sh

openSUSE needs to open SFW2 also for iperf3 testing only, not just iperf3 plus Loadbal test.

Open Firewall on openSUSE for iperf3 also w/o LB testing.

---

api_monitor.sh
run_wave.sh

This results in defaults from your cloud being used, which often is a good choice. Use this for the wavestack cloud.

Allow NOT supplying nameservers to subnets.

---

api_monitor.sh

Only the resources waited for in waitlistResources would be properly reported to telegraf/influx/grafana, there was a typo in the ones waited for in waitResources. This cause waitJHPORT not to be visible in grafana. Fixed.

Fix wait time reporting in waitResources.

---

api_monitor.sh

This is an attempt to work around a situation where the FIP assignment that happens during the JumpHost VM booting and downloading packages (triggered by cloud-init userdata) does disrupt communication for a while.

Assign Floating IPs earlier after JHVM creation.

---

api_monitor.sh
run_otc.sh

This was required on OTC, and we can still force the waiting by setting the FIPWAITPORTDEVOWNER environment.

Only wait for JHPORT b/f assigning FIP if needed.

---

api_monitor.sh

So OSC-5.5.0 reports (`openstack server list -f json`):
```
[
{
"ID": "XXXXXXXXXXXXXXXXXXXXXXXXXXXXXX",
"Name": "HealthMon-Host",
"Networks": {
"kd500924-SCS-healthmonitor-network": [
"192.168.0.17",
"78.138.66.252"
]
}
}
]
```
whereas older version OSC-5.3.1 reports
```
[
{
"ID": "XXXXXXXXXXXXXXXXXXXXXXXXX",
"Name": "testkg2",
"Networks": "testkg2=192.168.33.95, 31.172.117.55",
}
]
```
Adjust IP parser to handle both ...

Medium old OSC reports Networks in a diff format.

---

api_monitor.sh

Cosmetic. This was missing from ed808bba.

When outputting codes for cols, we need echo -e.

---

api_monitor.sh

Previously, we tried to use several, confusing numerous followup commands.

If there are multiple external nets, use the first.

---

startup/README.md
startup/apimon.service
startup/kill-apimon-in-tmux.sh
startup/run-apimon-in-tmux.sh

Even with some docu.
This one was a bit of work:
* Create a tmux script that starts a tmux session and pushed some commands into it to start run_in_loop.sh which calls run_YOURCLOUD.sh which calls api_monitor.sh
* There's also a kill script that sends ^C, so cleanup can start happening.
* There is a systemd file, meant to be installed into the `--user` systemd logic
* And documentation that explains how to use it, including the important
`sudo loginctl enable-linger $USER` command which I learned doing this.

Add user systemd unit and tmux start scripts.

---

README.md
api_monitor.sh

New option -LR does this.
The OVN loadbalancer in Bobcat+OVN-24.03.1 leaks ports (ovn-lb-hm-$SUBNETD) if the members are deleted before the healthmonitor. This is reported as OSISM issue #921.

Optionally reverse order of LB HM and member creation.

---

api_monitor.sh

Some environments' storage is not fast enough to be reported in MiB/s. Our regexes don't match then, so retry with KiB/s.

Support fio output in KiB/s.

---

docs/Debian12-Install.md

It seems that the guide is now only available for CentOS.
Closes #187

docs: remove broken link

---

docs/Debian12-Install.md

Adds documentation to use Caddy with automatic Let's Encrypt certs in front of Grafana. Caddy still uses port 3000, Grafana only listens locally on 3003.
I also tried to improve some other minor things that occured to me while I set up the OSHM for PoC WG-Cloud.
Resolves: #193

Document caddy reverse proxy setup
